# Generated by Django 3.2.9 on 2021-12-02 21:09

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='phone',
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='count',
            field=models.IntegerField(default=0, help_text='Number of otp sent'),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 14 digits allowed.", regex='^\\+?1?\\d{4,14}$')]),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='txn_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '[6,7,8,9]xxxxxxxxx'. Approx 10 digits allowed.", regex='^[6-9]\\d{9}$')]),
        ),
    ]
