# Generated by Django 3.2.9 on 2021-12-02 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211203_0202'),
        ('accounts', '0005_auto_20211203_0239'),
    ]

    operations = [
    ]
