# Generated by Django 3.2.9 on 2021-12-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_0005_auto_20211203_0202_0005_auto_20211203_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_progress',
            field=models.IntegerField(choices=[(1, 'OTP-Pending'), (2, 'OTP-Verified'), (3, 'Shop-Pending'), (4, 'Shop-Verified'), (5, 'Permissions-Pending'), (6, 'Permissions-Verified'), (7, 'InitialMessages-Pending'), (8, 'InitialMessages-Verified'), (9, 'UserInvite-Pending'), (10, 'UserInvite-Done')], default=1, null=True),
        ),
    ]
