# Generated by Django 3.2.9 on 2021-12-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_profile_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='razorpay_contact_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='razorpay_fund_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
