# Generated by Django 3.2.9 on 2021-12-03 19:22

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211203_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
