# Generated by Django 3.2.9 on 2021-12-03 19:33

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_shop_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='unique_code',
            field=models.CharField(default=accounts.utils.random_string, max_length=8, unique=True),
        ),
    ]
