# Generated by Django 3.2.9 on 2021-12-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20211204_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='razorpay_processed',
            field=models.BooleanField(default=False),
        ),
    ]
