# Generated by Django 3.2.9 on 2021-12-04 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userbankaccount_razorpay_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='verified_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
