# Generated by Django 3.2.9 on 2021-12-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_userbankaccount_verified_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
