# Generated by Django 3.2.9 on 2021-12-04 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20211204_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.shop'),
        ),
    ]
