# Generated by Django 3.2.9 on 2021-12-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payouttransaction',
            name='razorpay_payout_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
