# Generated by Django 3.2.9 on 2021-12-03 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('attendance_time_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendance_time_out', models.DateTimeField(blank=True, null=True)),
                ('attendance_time_in_location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('attendance_time_out_location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('attendance_time_in_selfie', models.ImageField(upload_to='attendance/in/%d-%m-%Y/')),
                ('attendance_time_out_selfie', models.ImageField(upload_to='attendance/out/%d-%m-%Y/')),
                ('attendance_processed', models.BooleanField(default=False)),
                ('verified_face', models.BooleanField(default=False)),
                ('verified_location', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
