# Generated by Django 3.2.9 on 2021-12-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='absent',
            field=models.BooleanField(default=False),
        ),
    ]
